SGX simulation build (#196)
- Added simulator-only seal and unseal implementations (seal/unseal is unsupported in simulation mode and errors out)
- Added simulation build script
- Added separate simulation configuration file
- Ignoring SGX data files

diff --git a/firmware/build/build-sgx b/firmware/build/build-sgx
--- a/firmware/build/build-sgx
+++ b/firmware/build/build-sgx
@@ -1,5 +1,15 @@
 #! /usr/bin/env bash
 
+BUILD_TARGET=build
+if [[ "$(basename $0)" == "build-sgx-debug" ]]; then
+    BUILD_TARGET=build-debug
+elif [[ "$(basename $0)" == "build-sgx-sim" ]]; then
+    BUILD_TARGET=build-sim
+elif [[ "$(basename $0)" != "build-sgx" ]]; then
+    echo "Invalid build script"
+    exit 1
+fi
+
 if [[ $# -lt 3 ]]; then
     echo "Usage: $0 <checkpoint> <minimum_difficulty> <network>"
     exit 1
@@ -25,10 +35,6 @@ HSM_ROOT=$(realpath $BUILD_ROOT/../../)
 DOCKER_IMAGE=hsm:sgx
 source $BUILD_ROOT/../../docker/check-image
 
-BUILD_TARGET=build
-if [[ "$(basename $0)" == "build-sgx-debug" ]]; then
-    BUILD_TARGET=build-debug
-fi
 BUILD_CMD="\$SGX_ENVSETUP && make clean $BUILD_TARGET CHECKPOINT=$1 TARGET_DIFFICULTY=$2 NETWORK=$NETWORK"
 
 DOCKER_USER="$(id -u):$(id -g)"
